### listar usuário
GET http://localhost:8080/fichas-tecnicas


### Criar usuário
POST http://localhost:8080/fichas-tecnicas
Content-Type: application/json

{
  "nomePreparo": "Lasanha",
  "tempoIdeal": 40,
  "temperaturaIdeal": 180
}

### Buscar usuário por ID
GET http://localhost:8080/fichas-tecnicas

### Atualizar usuário
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "Laura Atualizada",
  "email": "laura.atualizada@email.com"
}

### Deletar usuário
DELETE http://localhost:8080/fichas-tecnicas/e878f382-9391-4e32-a3c9-dc805a15b33e