### listar usuário
GET http://localhost:8080/usuarios


### Criar usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Laura",
  "email": "laura@email.com"
}

### Buscar usuário por ID
GET http://localhost:8080/usuarios/1

### Atualizar usuário
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "Laura Atualizada",
  "email": "laura.atualizada@email.com"
}

### Deletar usuário
DELETE http://localhost:8080/usuarios/1